name: LMI-Dist dependency build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-runners-g5:
    runs-on: [ self-hosted, scheduler ]
    steps:
      - name: Create new G5 instance
        id: create_gpu
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          token=$( curl -X POST -H "Authorization: token ${{ secrets.ACTION_RUNNER_PERSONAL_TOKEN }}" \
          https://api.github.com/repos/deepjavalibrary/djl-serving/actions/runners/registration-token \
          --fail \
          | jq '.token' | tr -d '"' )
          ./start_instance.sh action_g5 $token djl-serving
    outputs:
      gpu_instance_id_1: ${{ steps.create_gpu.outputs.action_g5_instance_id }}

  lmi-deps-build:
    runs-on: [ self-hosted, g5 ]
    container:
      image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
      options: --gpus all --runtime=nvidia --shm-size 20g
    timeout-minutes: 35
    needs: create-runners-g5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          apt-get update
          apt-get install -y software-properties-common wget libaio-dev g++ git gcc
          mkdir build_artifacts
      - name: Set up Python3
        run: |
          ./serving/docker/scripts/install_python.sh 3.10
      - name: Install torch dependencies
        run: |
          python -m venv venv
          . ./venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install numpy cmake awscli packaging wheel setuptools ninja \
          git-remote-codecommit torch==2.1.2 --extra-index-url https://download.pytorch.org/whl/cu121
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185921645874:role/github-actions-djl-serving
          aws-region: us-east-1
      - name: Build vllm 0.3.3 speculative decoding
        run: |
          . ./venv/bin/activate
          git clone https://github.com/xyang16/vllm.git -b embedding
          cd vllm
          export TORCH_CUDA_ARCH_LIST="7.5 8.0 8.6 8.9 9.0+PTX"
          export VLLM_INSTALL_PUNICA_KERNELS=1
          pip wheel . --no-deps
          cp vllm-*.whl ../build_artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build_artifacts/

  stop-runners-g5:
    if: always()
    runs-on: [ self-hosted, scheduler ]
    needs: [ create-runners-g5, lmi-deps-build ]
    steps:
      - name: Stop all instances
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          instance_id=${{ needs.create-runners.outputs.gpu_instance_id_1 }}
          ./stop_instance.sh $instance_id
